python train.py \
    --batch_size 1 \
    --gpu_ids 0 \
    --name contrast2no \
    --dataroot datasets/contrast2no \
    --input_nc 1 \
    --output_nc 1 \
    --load_size 512 \
    --crop_size 512 \
    --display_winsize 512 ;
